rvois = [
    "repthon/helpers/styles/meme/ابو عباس لو تاكل خره.ogg",
    "repthon/helpers/styles/meme/استمر نحن معك.ogg",
    "repthon/helpers/styles/meme/افحط بوجه.ogg",
    "repthon/helpers/styles/meme/اكعد لا اسطرك سطره العباس.ogg",
    "repthon/helpers/styles/meme/اللهم لا شماته.ogg",
    "repthon/helpers/styles/meme/امرع دينه.ogg",
    "repthon/helpers/styles/meme/امشي بربوك.ogg",
    "repthon/helpers/styles/meme/انت اسكت انت اسكت.ogg",
    "repthon/helpers/styles/meme/انت سايق زربه.ogg",
    "repthon/helpers/styles/meme/اوني تشان.ogg",
    "repthon/helpers/styles/meme/برافو عليك استادي.ogg",
    "repthon/helpers/styles/meme/بلوك محترم.ogg",
    "repthon/helpers/styles/meme/بووم في منتصف الجبهة.ogg",
    "repthon/helpers/styles/meme/بيتش.ogg",
    "repthon/helpers/styles/meme/تره متكدرلي.ogg",
    "repthon/helpers/styles/meme/تعبان اوي.ogg",
    "repthon/helpers/styles/meme/تكذب.ogg",
    "repthon/helpers/styles/meme/حسبي الله.ogg",
    "repthon/helpers/styles/meme/حشاش.ogg",
    "repthon/helpers/styles/meme/حقير.ogg",
    "repthon/helpers/styles/meme/خاص.ogg",
    "repthon/helpers/styles/meme/خاله ما تنامون.ogg",
    "repthon/helpers/styles/meme/خرب شرفي اذا ابقى بالعراق.ogg",
    "repthon/helpers/styles/meme/دكات الوكت الاغبر.ogg",
    "repthon/helpers/styles/meme/ررردح.ogg",
    "repthon/helpers/styles/meme/سلامن عليكم.ogg",
    "repthon/helpers/styles/meme/شعليك.ogg",
    "repthon/helpers/styles/meme/شكد شفت ناس مدودة.ogg",
    "repthon/helpers/styles/meme/شلون ،.ogg",
    "repthon/helpers/styles/meme/صح لنوم.ogg",
    "repthon/helpers/styles/meme/صمت.ogg",
    "repthon/helpers/styles/meme/ضحكة مصطفى الحجي.ogg",
    "repthon/helpers/styles/meme/طماطه.ogg",
    "repthon/helpers/styles/meme/طيح الله حضك.ogg",
    "repthon/helpers/styles/meme/فاك يوو.ogg",
    "repthon/helpers/styles/meme/فرحان.ogg",
    "repthon/helpers/styles/meme/لا تضل تضرط.ogg",
    "repthon/helpers/styles/meme/لا تقتل المتعه يا مسلم.ogg",
    "repthon/helpers/styles/meme/لا مستحيل.ogg",
    "repthon/helpers/styles/meme/لا والله شو عصبي.ogg",
    "repthon/helpers/styles/meme/لش.ogg",
    "repthon/helpers/styles/meme/لك اني شعليه.ogg",
    "repthon/helpers/styles/meme/ما اشرب.ogg",
    "repthon/helpers/styles/meme/مع الاسف.ogg",
    "repthon/helpers/styles/meme/مقتدى.ogg",
    "repthon/helpers/styles/meme/من رخصتكم.ogg",
    "repthon/helpers/styles/meme/منو انت.ogg",
    "repthon/helpers/styles/meme/منورني.ogg",
    "repthon/helpers/styles/meme/نتلاكه بالدور الثاني.ogg",
    "repthon/helpers/styles/meme/نستودعكم الله.ogg",
    "repthon/helpers/styles/meme/ها شنهي.ogg",
    "repthon/helpers/styles/meme/ههاي الافكار حطها.ogg",
    "repthon/helpers/styles/meme/وينهم.ogg",
    "repthon/helpers/styles/meme/يموتون جهالي.ogg",
    "repthon/helpers/styles/meme/اريد انام.ogg",
    "repthon/helpers/styles/meme/افتحك فتح.ogg",
    "repthon/helpers/styles/meme/اكل خره لدوخني.ogg",
    "repthon/helpers/styles/meme/السيد شنهو السيد.ogg",
    "repthon/helpers/styles/meme/زيج2.ogg",
    "repthon/helpers/styles/meme/زيج لهارون.ogg",
    "repthon/helpers/styles/meme/زيج الناصرية.ogg",
    "repthon/helpers/styles/meme/راقبو اطفالكم.ogg",
    "repthon/helpers/styles/meme/راح اموتن.ogg",
    "repthon/helpers/styles/meme/ذس اس مضرطة.ogg",
    "repthon/helpers/styles/meme/دروح سرسح منا.ogg",
    "repthon/helpers/styles/meme/خويه ما دكوم بيه.ogg",
    "repthon/helpers/styles/meme/خلصت تمسلت ديلة كافي انجب.ogg",
    "repthon/helpers/styles/meme/بعدك تخاف.ogg",
    "repthon/helpers/styles/meme/بسبوس.ogg",
    "repthon/helpers/styles/meme/اني بتيتة كحبة.ogg",
    "repthon/helpers/styles/meme/انعل ابوكم لابو اليلعب وياكم طوبة.ogg",
    "repthon/helpers/styles/meme/انت شدخلك.ogg",
    "repthon/helpers/styles/meme/انا ماشي بطلع.ogg",
    "repthon/helpers/styles/meme/امداك وامده الخلفتك.ogg",
    "repthon/helpers/styles/meme/امبيههههه.ogg",
    "repthon/helpers/styles/meme/هدي بيبي.ogg",
    "repthon/helpers/styles/meme/هاه صدك تحجي.ogg",
    "repthon/helpers/styles/meme/مو كتلك رجعني.ogg",
    "repthon/helpers/styles/meme/مامرجية منك هاية.ogg",
    "repthon/helpers/styles/meme/ليش هيجي.ogg",
    "repthon/helpers/styles/meme/كـــافـي.ogg",
    "repthon/helpers/styles/meme/كس اخت السيد.ogg",
    "repthon/helpers/styles/meme/شنو كواد ولك اني هنا.ogg",
    "repthon/helpers/styles/meme/شجلبت.ogg",
    "repthon/helpers/styles/meme/شبيك وجه الدبس.ogg",
    "repthon/helpers/styles/meme/سييييي.ogg",
    "repthon/helpers/styles/meme/زيجج1.ogg",
    "repthon/helpers/styles/meme/يموتون جهالي.ogg",
    "repthon/helpers/styles/meme/ياخي اسكت اسكت.ogg",
    "repthon/helpers/styles/meme/وينهم.ogg",
    "repthon/helpers/styles/meme/هيلو سامر وحود.ogg",
    "repthon/helpers/styles/meme/هو.ogg",
    "repthon/helpers/styles/meme/ههاي الافكار حطها.ogg",
]
